name: Vite GitHub Pages Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vite GitHub Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.3.0
        id: deploy_to_pages
